-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.12-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para challenge
CREATE DATABASE IF NOT EXISTS `challenge` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `challenge`;

-- Volcando estructura para tabla challenge.zip_codes
CREATE TABLE IF NOT EXISTS `zip_codes` (
  `id_zipcode` int(11) NOT NULL AUTO_INCREMENT,
  `zip_code` varchar(50) NOT NULL DEFAULT '0',
  `federal_entity` varchar(50) NOT NULL DEFAULT '0',
  `municipality` varchar(50) NOT NULL DEFAULT '0',
  `locality` varchar(50) NOT NULL DEFAULT '0',
  `settlement` varchar(50) NOT NULL DEFAULT '0',
  `settlement_type` varchar(50) NOT NULL DEFAULT '0',
  `clave_oficina` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_zipcode`)
) ENGINE=InnoDB AUTO_INCREMENT=491 DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla challenge.zip_codes: ~165 rows (aproximadamente)
/*!40000 ALTER TABLE `zip_codes` DISABLE KEYS */;
INSERT INTO `zip_codes` (`id_zipcode`, `zip_code`, `federal_entity`, `municipality`, `locality`, `settlement`, `settlement_type`, `clave_oficina`) VALUES
	(2, '16080', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Santísima', 'Barrio', '16001'),
	(3, '16080', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Cristóbal', 'Barrio', '16001'),
	(4, '16080', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Diego', 'Barrio', '16001'),
	(5, '16080', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Esteban', 'Barrio', '16001'),
	(6, '16090', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Pedro', 'Barrio', '16001'),
	(7, '16090', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Tablas de San Lorenzo', 'Colonia', '16001'),
	(8, '16090', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Xaltocan', 'Barrio', '16001'),
	(9, '16100', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Cruz Xochitepec', 'Pueblo', '16001'),
	(10, '16200', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santiago Tepalcatlalpan', 'Pueblo', '16001'),
	(11, '16210', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Concha', 'Colonia', '16001'),
	(12, '16300', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Lucas Xochimanca', 'Pueblo', '16001'),
	(13, '16310', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Cañada', 'Colonia', '16001'),
	(14, '16320', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Lucas Oriente', 'Colonia', '16001'),
	(15, '16340', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Texmic', 'Colonia', '16001'),
	(16, '16400', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Lorenzo Atemoaya', 'Pueblo', '16001'),
	(17, '16410', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Lomas de Tonalco', 'Colonia', '16001'),
	(18, '16420', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Jerónimo', 'Colonia', '16001'),
	(19, '16428', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'El Jazmín', 'Colonia', '16001'),
	(20, '16429', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Rancho Tejomulco', 'Colonia', '16001'),
	(21, '16430', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Xochipilli', 'Colonia', '16001'),
	(22, '16440', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Año de Juárez', 'Colonia', '16001'),
	(23, '16443', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Pocitos', 'Barrio', '16001'),
	(24, '16450', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa María Nativitas', 'Pueblo', '16001'),
	(25, '16457', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Lomas de Nativitas', 'Colonia', '16001'),
	(26, '16459', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Ampliación Nativitas', 'Colonia', '16001'),
	(27, '16500', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Cruz Acalpixca', 'Pueblo', '16001'),
	(28, '16513', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Apatlaco', 'Barrio', '16001'),
	(29, '16513', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Del Puente', 'Barrio', '16001'),
	(30, '16514', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Gallera', 'Barrio', '16001'),
	(31, '16514', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Tetitla', 'Barrio', '16001'),
	(32, '16514', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Calpulco', 'Barrio', '16001'),
	(33, '16520', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Planta', 'Barrio', '16001'),
	(34, '16530', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Las Cruces', 'Barrio', '16001'),
	(35, '16530', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Las Flores', 'Barrio', '16001'),
	(36, '16533', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Ahualapa', 'Barrio', '16001'),
	(37, '16550', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Valle de Santa María', 'Colonia', '16001'),
	(38, '16600', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Gregorio Atlapulco', 'Pueblo', '16001'),
	(39, '16604', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Andrés', 'Barrio', '16001'),
	(40, '16605', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Los Reyes', 'Barrio', '16001'),
	(41, '16606', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', '3 de Mayo', 'Barrio', '16001'),
	(42, '16607', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Antonio', 'Barrio', '16001'),
	(43, '16609', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Candelaria', 'Barrio', '16001'),
	(44, '16610', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Luis Tlaxialtemalco', 'Pueblo', '16001'),
	(45, '16614', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Niños Héroes', 'Barrio', '16001'),
	(46, '16615', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Asunción', 'Barrio', '16001'),
	(47, '16616', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Cecilia', 'Barrio', '16001'),
	(48, '16617', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Sebastián', 'Barrio', '16001'),
	(49, '16620', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San José', 'Barrio', '16001'),
	(50, '16629', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'La Guadalupana', 'Barrio', '16001'),
	(51, '16629', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Juan', 'Barrio', '16001'),
	(52, '16630', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Juan Moyotepec', 'Barrio', '16001'),
	(53, '16640', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Juan Minas', 'Barrio', '16001'),
	(54, '16710', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Quirino Mendoza', 'Colonia', '16001'),
	(55, '16720', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Del Carmen', 'Colonia', '16001'),
	(56, '16739', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Isidro', 'Colonia', '16001'),
	(57, '16740', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Guadalupita', 'Colonia', '16001'),
	(58, '16749', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Las Animas', 'Colonia', '16001'),
	(59, '16750', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Calyequita', 'Barrio', '16001'),
	(60, '16770', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Felipe', 'Colonia', '16001'),
	(61, '16776', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santiaguito', 'Colonia', '16001'),
	(62, '16776', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'El Mirador', 'Colonia', '16001'),
	(63, '16780', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Cerrillos Primera Sección', 'Colonia', '16001'),
	(64, '16780', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'El Sacrificio', 'Colonia', '16001'),
	(65, '16780', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Cristo Rey', 'Colonia', '16001'),
	(66, '16780', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Cerrillos Segunda Sección', 'Colonia', '16001'),
	(67, '16780', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Cerrillos Tercera Sección', 'Colonia', '16001'),
	(68, '16797', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Nativitas', 'Colonia', '16001'),
	(69, '16799', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Las Mesitas', 'Colonia', '16001'),
	(70, '16800', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Mateo Xalpa', 'Pueblo', '16001'),
	(71, '16810', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Andrés Ahuayucan', 'Pueblo', '16001'),
	(72, '16810', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Inés', 'Colonia', '16001'),
	(73, '16810', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Rosario Tlali', 'Colonia', '16001'),
	(74, '16813', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'El Calvario', 'Barrio', '16001'),
	(75, '16840', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Cruz Chavarrieta', 'Colonia', '16001'),
	(76, '16850', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Chapultepec', 'Barrio', '16001'),
	(77, '16860', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Cruz de Guadalupe', 'Colonia', '16001'),
	(78, '16880', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'Santa Cecilia Tepetlapa', 'Pueblo', '16001'),
	(79, '16900', 'Ciudad de México', 'Xochimilco', 'Ciudad de México', 'San Francisco Tlalnepantla', 'Pueblo', '16001'),
	(80, '2480', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Petrolera', 'Colonia', '2011'),
	(81, '2490', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Mateo', 'Barrio', '2011'),
	(82, '2500', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Unidad Cuitlahuac', 'Colonia', '2011'),
	(83, '2519', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'El Jagüey', 'Colonia', '2011'),
	(84, '2520', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Estación Pantaco', 'Equipamiento', '2601'),
	(85, '2530', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Jardín Azpeitia', 'Colonia', '2011'),
	(86, '2600', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Pro-Hogar', 'Colonia', '2601'),
	(87, '2630', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Coltongo', 'Barrio', '2601'),
	(88, '2630', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Coltongo', 'Colonia', '2601'),
	(89, '2640', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Monte Alto', 'Colonia', '2601'),
	(90, '2650', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Trabajadores de Hierro', 'Colonia', '2601'),
	(91, '2660', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Euzkadi', 'Colonia', '2601'),
	(92, '2670', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Cosmopolita', 'Colonia', '2601'),
	(93, '2680', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Potrero del Llano', 'Colonia', '2601'),
	(94, '2700', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Miguel Amantla', 'Pueblo', '2011'),
	(95, '2710', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Pedro Xalpa', 'Pueblo', '2011'),
	(96, '2719', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Ampliación San Pedro Xalpa', 'Colonia', '2011'),
	(97, '2720', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Antonio', 'Colonia', '2011'),
	(98, '2720', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Bartolo Cahualtongo', 'Pueblo', '2011'),
	(99, '2730', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Francisco Tetecala', 'Pueblo', '2011'),
	(100, '2750', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Santiago Ahuizotla', 'Pueblo', '2011'),
	(101, '2760', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Industrial San Antonio', 'Colonia', '2011'),
	(102, '2760', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Santa Lucía', 'Barrio', '2011'),
	(103, '2770', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Santa Cruz Acayucan', 'Pueblo', '2011'),
	(104, '2780', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Plenitud', 'Colonia', '2011'),
	(105, '2790', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Santa Apolonia', 'Barrio', '2011'),
	(106, '2800', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Nueva Santa María', 'Colonia', '2601'),
	(107, '2810', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Ignacio Allende', 'Colonia', '2601'),
	(108, '2810', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Victoria de las Democracias', 'Colonia', '2601'),
	(109, '2830', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Bernabé', 'Barrio', '2601'),
	(110, '2840', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Obrero Popular', 'Colonia', '2601'),
	(111, '2860', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Tlatilco', 'Colonia', '2601'),
	(112, '2870', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Salvador Xochimanca', 'Colonia', '2601'),
	(113, '2900', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Aguilera', 'Colonia', '2601'),
	(114, '2910', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Aldana', 'Colonia', '2601'),
	(115, '2920', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Ampliación Cosmopolita', 'Colonia', '2601'),
	(116, '2930', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Liberación', 'Colonia', '2601'),
	(117, '2940', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Porvenir', 'Colonia', '2601'),
	(118, '2950', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Del Gas', 'Colonia', '2601'),
	(119, '2960', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'San Francisco Xocotitla', 'Pueblo', '2601'),
	(120, '2970', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Ampliación Del Gas', 'Colonia', '2601'),
	(121, '2980', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Arenal', 'Colonia', '2601'),
	(122, '2980', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'Patrimonio Familiar', 'Colonia', '2601'),
	(123, '2990', 'Ciudad de México', 'Azcapotzalco', 'Ciudad de México', 'La Raza', 'Colonia', '2601'),
	(124, '3000', 'Ciudad de México', 'Benito Juárez', 'Ciudad de México', 'Piedad Narvarte', 'Colonia', '3001'),
	(125, '3010', 'Ciudad de México', 'Benito Juárez', 'Ciudad de México', 'Atenor Salas', 'Colonia', '3001'),
	(126, '3020', 'Ciudad de México', 'Benito Juárez', 'Ciudad de México', 'Narvarte Poniente', 'Colonia', '3001'),
	(127, '3023', 'Ciudad de México', 'Benito Juárez', 'Ciudad de México', 'Narvarte Oriente', 'Colonia', '3001'),
	(128, '3100', 'Ciudad de México', 'Benito Juárez', 'Ciudad de México', 'Del Valle Centro', 'Colonia', '3001'),
	(129, '7180', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Cocoyotes', 'Colonia', '7201'),
	(130, '7180', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'General Felipe Berriozabal', 'Colonia', '7201'),
	(131, '7180', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ampliación Cocoyotes', 'Colonia', '7201'),
	(132, '7183', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', '6 de Junio', 'Colonia', '7201'),
	(133, '7187', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Vista Hermosa', 'Colonia', '7201'),
	(134, '7188', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Tlalpexco', 'Colonia', '7201'),
	(135, '7189', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ahuehuetes', 'Colonia', '7201'),
	(136, '7190', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Valle de Madero', 'Colonia', '7201'),
	(137, '7199', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Del Carmen', 'Colonia', '7201'),
	(138, '7200', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Cuautepec de Madero', 'Colonia', '7201'),
	(139, '7207', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Del Bosque', 'Colonia', '7201'),
	(140, '7209', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Guadalupe Victoria Cuautepec', 'Colonia', '7201'),
	(141, '7210', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Chalma de Guadalupe', 'Colonia', '7201'),
	(142, '7214', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ampliación Chalma de Guadalupe', 'Colonia', '7201'),
	(143, '7220', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Castillo Chico', 'Colonia', '7201'),
	(144, '7220', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Castillo Grande', 'Colonia', '7201'),
	(145, '7224', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ampliación Castillo Grande', 'Colonia', '7201'),
	(146, '7230', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Zona Escolar', 'Colonia', '7201'),
	(147, '7239', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Zona Escolar Oriente', 'Colonia', '7201'),
	(148, '7240', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'El Arbolillo', 'Colonia', '7201'),
	(149, '7250', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Benito Juárez', 'Colonia', '7201'),
	(150, '7259', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ampliación Benito Juárez', 'Colonia', '7201'),
	(151, '7268', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Solidaridad Nacional', 'Colonia', '7201'),
	(152, '7270', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Residencial Acueducto de Guadalupe', 'Colonia', '7201'),
	(153, '7279', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Acueducto de Guadalupe', 'Colonia', '7201'),
	(154, '7280', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Jorge Negrete', 'Colonia', '7201'),
	(155, '7290', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'La Pastora', 'Colonia', '7201'),
	(156, '7300', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Lindavista Norte', 'Colonia', '7051'),
	(157, '7300', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Lindavista Sur', 'Colonia', '7051'),
	(158, '7310', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Candelaria Ticomán', 'Barrio', '7311'),
	(159, '7320', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'La Purísima Ticomán', 'Barrio', '7311'),
	(160, '7320', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Residencial la Escalera', 'Colonia', '7311'),
	(161, '7330', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Santa María Ticomán', 'Colonia', '7311'),
	(162, '7340', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'La Laguna Ticomán', 'Barrio', '7311'),
	(163, '7340', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San José Ticomán', 'Colonia', '7311'),
	(164, '7350', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Guadalupe Ticomán', 'Barrio', '7311'),
	(165, '7350', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan y Guadalupe Ticomán', 'Barrio', '7311'),
	(166, '7359', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Rafael Ticomán', 'Barrio', '7311'),
	(167, '7370', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Capultitlan', 'Colonia', '7001'),
	(168, '7380', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Maximino Ávila Camacho', 'Colonia', '7001'),
	(169, '7380', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Tlacamaca', 'Colonia', '7001'),
	(170, '7400', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Salvador Díaz Mirón', 'Colonia', '7001'),
	(171, '7410', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Juan González Romero', 'Colonia', '7001'),
	(172, '7410', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Villa Hermosa', 'Colonia', '7001'),
	(173, '7420', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'El Coyol', 'Colonia', '7001'),
	(174, '7420', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Nueva Atzacoalco', 'Colonia', '7001'),
	(175, '7430', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Del Obrero', 'Colonia', '7001'),
	(176, '7440', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Vasco de Quiroga', 'Colonia', '7001'),
	(177, '7450', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'DM Nacional', 'Colonia', '7001'),
	(178, '7455', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ferrocarrilera', 'Colonia', '7001'),
	(179, '7456', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'LI Legislatura', 'Colonia', '7001'),
	(180, '7460', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Granjas Modernas', 'Colonia', '7001'),
	(181, '7469', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Constitución de La República', 'Colonia', '7001'),
	(182, '9638', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Ampliación Emiliano Zapata', 'Colonia', '9511'),
	(183, '9640', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Lomas de la Estancia', 'Colonia', '9511'),
	(184, '9640', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Xalpa', 'Colonia', '9511'),
	(185, '9648', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'San Pablo', 'Colonia', '9511'),
	(186, '9660', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Citlalli', 'Colonia', '9511'),
	(187, '9670', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Palmitas', 'Colonia', '9511'),
	(188, '9680', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Tenorios', 'Colonia', '9511'),
	(189, '9689', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Barranca de Guadalupe', 'Colonia', '9511'),
	(190, '9690', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Iztlahuacán', 'Colonia', '9511'),
	(191, '9696', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Miravalles', 'Colonia', '9511'),
	(192, '9698', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Miguel de La Madrid Hurtado', 'Colonia', '9511'),
	(193, '9700', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Buenavista', 'Colonia', '9291'),
	(194, '9700', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Carlos Hank Gonzalez', 'Colonia', '9291'),
	(195, '9700', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Desarrollo Urbano Quetzalcoatl', 'Colonia', '9291'),
	(196, '9700', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Santa Cruz Meyehualco', 'Pueblo', '9291'),
	(197, '9704', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Degollado', 'Colonia', '9291'),
	(198, '9705', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Degollado - Mexicatlalli', 'Colonia', '9291'),
	(199, '9706', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'San José Buenavista', 'Colonia', '9291'),
	(200, '9708', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Mixcoatl', 'Colonia', '9291'),
	(201, '9709', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Lomas de Santa Cruz', 'Colonia', '9291'),
	(202, '9710', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Los Ángeles Apanoaya', 'Colonia', '9291'),
	(203, '9720', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Francisco Villa', 'Colonia', '9291'),
	(204, '9720', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'La Era', 'Colonia', '9291'),
	(205, '9730', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Reforma Política', 'Colonia', '9291'),
	(206, '9740', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Presidentes de México', 'Colonia', '9291'),
	(207, '9750', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Insurgentes', 'Colonia', '9291'),
	(208, '9750', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'La Polvorilla', 'Colonia', '9291'),
	(209, '9750', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Las Peñas', 'Colonia', '9291'),
	(210, '9760', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Consejo Agrarista Mexicano', 'Colonia', '9291'),
	(211, '9769', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'El Triángulo', 'Colonia', '9291'),
	(212, '9770', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Puente Blanco', 'Colonia', '9291'),
	(213, '9780', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Año de Juárez', 'Colonia', '9291'),
	(214, '9780', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Lomas de San Lorenzo', 'Colonia', '9291'),
	(215, '9790', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'San Lorenzo Tezonco', 'Pueblo', '9291'),
	(216, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Culhuacán', 'Pueblo', '9821'),
	(217, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'El Mirador', 'Colonia', '9821'),
	(218, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Estrella Culhuacán', 'Colonia', '9821'),
	(219, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Fuego Nuevo', 'Colonia', '9821'),
	(220, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'San Antonio Culhuacán', 'Colonia', '9821'),
	(221, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'San Antonio Culhuacán', 'Barrio', '9821'),
	(222, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'San Simón Culhuacán', 'Barrio', '9821'),
	(223, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Tula', 'Barrio', '9821'),
	(224, '9800', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Valle de Luces', 'Colonia', '9821'),
	(225, '9810', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Granjas Esmeralda', 'Colonia', '9821'),
	(226, '9810', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Los Cipreses', 'Colonia', '9821'),
	(227, '9810', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Minerva', 'Colonia', '9821'),
	(228, '9810', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Progreso del Sur', 'Colonia', '9821'),
	(229, '9819', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Valle del Sur', 'Colonia', '9821'),
	(230, '9820', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'El Santuario', 'Colonia', '9821'),
	(231, '9820', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Estrella del Sur', 'Colonia', '9821'),
	(232, '9820', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Ricardo Flores Magón', 'Colonia', '9821'),
	(233, '9820', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Santa Isabel Industrial', 'Colonia', '9821'),
	(234, '9828', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Ampliación Ricardo Flores Magón', 'Colonia', '9821'),
	(235, '9829', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'Ampliación El Santuario', 'Colonia', '9821'),
	(236, '9830', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'El Manto', 'Colonia', '9821'),
	(237, '9830', 'Ciudad de México', 'Iztapalapa', 'Ciudad de México', 'El Molino', 'Colonia', '9821'),
	(238, '7870', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Vallejo', 'Colonia', '7001'),
	(239, '7880', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Mártires de Río Blanco', 'Colonia', '7001'),
	(240, '7889', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Emiliano Zapata', 'Colonia', '7001'),
	(241, '7890', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Cuchilla La Joya', 'Colonia', '7001'),
	(242, '7890', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'La Joya', 'Colonia', '7001'),
	(243, '7890', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Nueva Tenochtitlán', 'Colonia', '7001'),
	(244, '7899', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'La Malinche', 'Colonia', '7001'),
	(245, '7900', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Cuchilla del Tesoro', 'Colonia', '7981'),
	(246, '7910', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón VII Sección', 'Colonia', '7981'),
	(247, '7918', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón VI Sección', 'Colonia', '7981'),
	(248, '7919', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ex Ejido San Juan de Aragón Sector 32', 'Colonia', '7981'),
	(249, '7920', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'El Olivo', 'Colonia', '7981'),
	(250, '7920', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón', 'Colonia', '7981'),
	(251, '7930', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Indeco', 'Colonia', '7981'),
	(252, '7939', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Héroes de Chapultepec', 'Colonia', '7981'),
	(253, '7940', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ex Ejido San Juan de Aragón Sector 33', 'Colonia', '7981'),
	(254, '7950', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón', 'Pueblo', '7981'),
	(255, '7960', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Héroes de Cerro Prieto', 'Colonia', '7981'),
	(256, '7960', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Ex Escuela de Tiro', 'Colonia', '7981'),
	(257, '7960', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Fernando Casas Alemán', 'Colonia', '7981'),
	(258, '7969', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón I Sección', 'Colonia', '7981'),
	(259, '7969', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón II Sección', 'Colonia', '7981'),
	(260, '7970', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón III Sección', 'Colonia', '7981'),
	(261, '7979', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón IV Sección', 'Colonia', '7981'),
	(262, '7979', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'San Juan de Aragón V Sección', 'Colonia', '7981'),
	(263, '7980', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'Narciso Bassols', 'Colonia', '7981'),
	(264, '7990', 'Ciudad de México', 'Gustavo A. Madero', 'Ciudad de México', 'C.T.M. Aragón', 'Colonia', '7981'),
	(265, '8000', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Gabriel Ramos Millán Sección Bramadero', 'Colonia', '8231'),
	(266, '8010', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Ex-Ejido de La Magdalena Mixiuhca', 'Colonia', '8231'),
	(267, '8020', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Ampliación Gabriel Ramos Millán', 'Colonia', '8231'),
	(268, '8030', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Gabriel Ramos Millán Sección Cuchilla', 'Colonia', '8231'),
	(269, '8040', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Carlos Zapata Vela', 'Colonia', '8231'),
	(270, '8100', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Agrícola Pantitlán', 'Colonia', '8231'),
	(271, '8200', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Viaducto Piedad', 'Colonia', '8231'),
	(272, '8210', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Nueva Santa Anita', 'Colonia', '8231'),
	(273, '8220', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'San Pedro', 'Barrio', '8231'),
	(274, '8230', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'San Francisco Xicaltongo', 'Barrio', '8231'),
	(275, '8240', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Santiago Norte', 'Barrio', '8231'),
	(276, '8300', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Santa Anita', 'Colonia', '8231'),
	(277, '8310', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'La Cruz', 'Colonia', '8231'),
	(278, '8320', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Fraccionamiento Coyuya', 'Colonia', '8231'),
	(279, '8400', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Granjas México', 'Colonia', '8231'),
	(280, '8420', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Cuchilla Agrícola Oriental', 'Colonia', '8231'),
	(281, '8500', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Agrícola Oriental', 'Colonia', '8231'),
	(282, '8510', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'El Rodeo', 'Colonia', '8231'),
	(283, '8600', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'La Asunción', 'Barrio', '8231'),
	(284, '8610', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Zapotla', 'Barrio', '8231'),
	(285, '8620', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Los Reyes', 'Barrio', '8231'),
	(286, '8650', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'San Miguel', 'Barrio', '8231'),
	(287, '8700', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Juventino Rosas', 'Colonia', '8231'),
	(288, '8710', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Tlazintla', 'Colonia', '8231'),
	(289, '8720', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Gabriel Ramos Millán Sección Tlacotal', 'Colonia', '8231'),
	(290, '8730', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'Gabriel Ramos Millán', 'Colonia', '8231'),
	(291, '8760', 'Ciudad de México', 'Iztacalco', 'Ciudad de México', 'INPI Picos', 'Colonia', '8231'),
	(292, '10368', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Ampliación Potrerillo', 'Colonia', '10581'),
	(293, '10369', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Ampliación Lomas de San Bernabé', 'Colonia', '10021'),
	(294, '10369', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Tierra Unida', 'Colonia', '10021'),
	(295, '10370', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Palmas', 'Colonia', '10021'),
	(296, '10378', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Atacaxco', 'Colonia', '10021'),
	(297, '10379', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Vista Hermosa', 'Colonia', '10021'),
	(298, '10380', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Barros Sierra', 'Colonia', '10021'),
	(299, '10400', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'San Jerónimo Aculco', 'Colonia', '10701'),
	(300, '10500', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Barrio San Francisco', 'Colonia', '10581'),
	(301, '10580', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Barranca Seca', 'Colonia', '10581'),
	(302, '10600', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'El Rosal', 'Colonia', '10581'),
	(303, '10610', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'El Toro', 'Colonia', '10581'),
	(304, '10620', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Potrerillo', 'Colonia', '10581'),
	(305, '10630', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'El Ocotal', 'Campamento', '10581'),
	(306, '10640', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'La Carbonera', 'Colonia', '10581'),
	(307, '10640', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Pueblo Nuevo Alto', 'Colonia', '10581'),
	(308, '10640', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Pueblo Nuevo Bajo', 'Colonia', '10581'),
	(309, '10660', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'El Ermitaño', 'Colonia', '10581'),
	(310, '10700', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Héroes de Padierna', 'Colonia', '10701'),
	(311, '10710', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Santa Teresa', 'Colonia', '10901'),
	(312, '10800', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'La Cruz', 'Colonia', '10581'),
	(313, '10810', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'San Francisco', 'Colonia', '10581'),
	(314, '10820', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'La Guadalupe', 'Colonia', '10901'),
	(315, '10830', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'La Concepción', 'Colonia', '10901'),
	(316, '10840', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Las Calles', 'Barrio', '10901'),
	(317, '10840', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Plazuela del Pedregal', 'Barrio', '10901'),
	(318, '10900', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'San Nicolás Totolapan', 'Pueblo', '10901'),
	(319, '10910', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'La Magdalena', 'Pueblo', '10581'),
	(320, '10920', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Las Huertas', 'Colonia', '10901'),
	(321, '10926', 'Ciudad de México', 'La Magdalena Contreras', 'Ciudad de México', 'Tierra Colorada', 'Campamento', '10901'),
	(322, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec I Sección', 'Colonia', '11801'),
	(323, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec VIII Sección', 'Colonia', '11801'),
	(324, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec II Sección', 'Colonia', '11801'),
	(325, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec III Sección', 'Colonia', '11801'),
	(326, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec IV Sección', 'Colonia', '11801'),
	(327, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec V Sección', 'Colonia', '11801'),
	(328, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec VI Sección', 'Colonia', '11801'),
	(329, '11000', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Chapultepec VII Sección', 'Colonia', '11801'),
	(330, '11040', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Molino del Rey', 'Colonia', '11801'),
	(331, '11100', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Bosque de Chapultepec II Sección', 'Equipamiento', '11801'),
	(332, '11100', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Bosque de Chapultepec III Sección', 'Equipamiento', '11801'),
	(333, '11200', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas Hermosa', 'Colonia', '11411'),
	(334, '11200', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Lomas de Sotelo', 'Colonia', '11411'),
	(335, '11210', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'San Lorenzo Tlaltenango', 'Pueblo', '11411'),
	(336, '11220', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Periodista', 'Colonia', '11411'),
	(337, '11230', 'Ciudad de México', 'Miguel Hidalgo', 'Ciudad de México', 'Argentina Poniente', 'Colonia', '11411'),
	(338, '1220', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Estrella', 'Colonia', '1401'),
	(339, '1230', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Campo de Tiro los Gamitos', 'Colonia', '1401'),
	(340, '1230', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Los Gamitos', 'Colonia', '1401'),
	(341, '1230', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tlapechico', 'Colonia', '1401'),
	(342, '1230', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Piru Santa Fe', 'Colonia', '1401'),
	(343, '1230', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Piru 2a Ampliación', 'Colonia', '1401'),
	(344, '1239', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Huerta', 'Colonia', '1401'),
	(345, '1240', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Pueblo Nuevo', 'Colonia', '1401'),
	(346, '1250', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Árbol', 'Colonia', '1401'),
	(347, '1250', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ladera', 'Colonia', '1401'),
	(348, '1250', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Nuevo México', 'Colonia', '1401'),
	(349, '1250', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Margarita Maza de Juárez', 'Colonia', '1401'),
	(350, '1250', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tecolalco', 'Colonia', '1401'),
	(351, '1259', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación La Cebada', 'Colonia', '1401'),
	(352, '1259', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Mexicana 2a Ampliación', 'Colonia', '1401'),
	(353, '1260', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Calzada Jalalpa', 'Colonia', '1401'),
	(354, '1260', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Mexicana', 'Colonia', '1401'),
	(355, '1260', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación La Mexicana', 'Colonia', '1401'),
	(356, '1260', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Palmita', 'Colonia', '1401'),
	(357, '1260', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Liberación Proletaria', 'Colonia', '1401'),
	(358, '1269', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '1a Sección Cañada', 'Colonia', '1401'),
	(359, '1269', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '2a Sección Cañada', 'Colonia', '1401'),
	(360, '1270', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Tejocote', 'Colonia', '1401'),
	(361, '1270', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Presa', 'Colonia', '1401'),
	(362, '1270', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Golondrinas', 'Colonia', '1401'),
	(363, '1270', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Golondrinas 1a Sección', 'Colonia', '1401'),
	(364, '1270', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Golondrinas 2a Sección', 'Colonia', '1401'),
	(365, '1270', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Capula', 'Colonia', '1401'),
	(366, '1275', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Villa Solidaridad', 'Colonia', '1401'),
	(367, '1276', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Pirul', 'Colonia', '1401'),
	(368, '1278', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Desarrollo Urbano', 'Colonia', '1401'),
	(369, '1279', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Becerra', 'Colonia', '1401'),
	(370, '1280', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Arvide', 'Colonia', '1401'),
	(371, '1280', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Pocito', 'Colonia', '1401'),
	(372, '1280', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Francisco Villa', 'Colonia', '1401'),
	(373, '1280', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Joya', 'Colonia', '1401'),
	(374, '1285', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Rodeo', 'Colonia', '1401'),
	(375, '1289', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Reacomodo El Cuernito', 'Colonia', '1401'),
	(376, '1290', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Piloto Adolfo López Mateos', 'Colonia', '1401'),
	(377, '1290', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Presidentes', 'Colonia', '1401'),
	(378, '1296', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Jalalpa Tepito 2a Ampliación', 'Colonia', '1401'),
	(379, '1296', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación Jalalpa', 'Colonia', '1401'),
	(380, '1296', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Jalalpa Tepito', 'Colonia', '1401'),
	(381, '1298', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación Piloto Adolfo López Mateos', 'Colonia', '1401'),
	(382, '1299', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '1a Ampliación Presidentes', 'Colonia', '1401'),
	(383, '1299', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '2a Ampliación Presidentes', 'Colonia', '1401'),
	(384, '1310', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Gabriel', 'Colonia', '1401'),
	(385, '1320', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Carlos A. Madrazo', 'Colonia', '1401'),
	(386, '1330', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Paseo de las Lomas', 'Colonia', '1401'),
	(387, '1340', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Bejero del Pueblo Santa Fe', 'Colonia', '1401'),
	(388, '1376', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Santa Fe', 'Colonia', '1401'),
	(389, '1376', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Santa Fe Peña Blanca', 'Colonia', '1401'),
	(390, '1376', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Santa Fe La Loma', 'Colonia', '1401'),
	(391, '1376', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Santa Fe Centro Ciudad', 'Colonia', '1401'),
	(392, '1377', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Jalalpa El Grande', 'Colonia', '1401'),
	(393, '1000', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Ángel', 'Colonia', '1001'),
	(394, '1010', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Los Alpes', 'Colonia', '1001'),
	(395, '1020', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Guadalupe Inn', 'Colonia', '1001'),
	(396, '1030', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Axotla', 'Pueblo', '1001'),
	(397, '1030', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Florida', 'Colonia', '1001'),
	(398, '1040', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Campestre', 'Colonia', '1001'),
	(399, '1049', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tlacopac', 'Pueblo', '1001'),
	(400, '1050', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ex-Hacienda de Guadalupe Chimalistac', 'Colonia', '1001'),
	(401, '1060', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Altavista', 'Colonia', '1001'),
	(402, '1060', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Ángel Inn', 'Colonia', '1001'),
	(403, '1070', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Chimalistac', 'Colonia', '1001'),
	(404, '1080', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Progreso Tizapan', 'Colonia', '1001'),
	(405, '1089', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ermita Tizapan', 'Colonia', '1001'),
	(406, '1090', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Otra Banda', 'Barrio', '1001'),
	(407, '1090', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Loreto', 'Barrio', '1001'),
	(408, '1090', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tizapan', 'Pueblo', '1001'),
	(409, '1100', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Pólvora', 'Colonia', '1131'),
	(410, '1109', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Conchita', 'Colonia', '1131'),
	(411, '1110', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Belém de las Flores', 'Colonia', '1131'),
	(412, '1110', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Capulín', 'Colonia', '1131'),
	(413, '1110', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación El Capulín', 'Colonia', '1131'),
	(414, '1110', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Liberales de 1857', 'Colonia', '1131'),
	(415, '1120', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Acueducto', 'Colonia', '1131'),
	(416, '1120', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Cove', 'Colonia', '1131'),
	(417, '1120', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Hidalgo', 'Colonia', '1131'),
	(418, '1120', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Las Américas', 'Colonia', '1131'),
	(419, '1125', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación Acueducto', 'Colonia', '1131'),
	(420, '1130', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Paraíso', 'Colonia', '1131'),
	(421, '1130', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Molino de Santo Domingo', 'Colonia', '1131'),
	(422, '1130', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Real del Monte', 'Colonia', '1131'),
	(423, '1139', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Reacomodo Pino Suárez', 'Colonia', '1131'),
	(424, '1140', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Bellavista', 'Colonia', '1131'),
	(425, '1140', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'José Maria Pino Suárez', 'Colonia', '1131'),
	(426, '1150', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Cristo Rey', 'Colonia', '1131'),
	(427, '1150', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tolteca', 'Colonia', '1131'),
	(428, '1160', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Bosque', 'Colonia', '1131'),
	(429, '1160', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Isidro Fabela', 'Colonia', '1131'),
	(430, '1160', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Maria G. de García Ruiz', 'Colonia', '1131'),
	(431, '1160', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '1a Victoria', 'Colonia', '1131'),
	(432, '1170', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Abraham M. González', 'Colonia', '1131'),
	(433, '1180', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Carola', 'Colonia', '1131'),
	(434, '1180', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '8 de Agosto', 'Colonia', '1131'),
	(435, '1180', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Pedro de los Pinos', 'Colonia', '1131'),
	(436, '1200', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Arturo Martínez', 'Colonia', '1401'),
	(437, '1210', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Santa Fe', 'Pueblo', '1401'),
	(438, '1219', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Santa Fe', 'Colonia', '1401'),
	(439, '1220', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Bonanza', 'Colonia', '1401'),
	(440, '1220', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Cuevitas', 'Colonia', '1401'),
	(441, '1220', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Cuernito', 'Colonia', '1401'),
	(442, '1220', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Mártires de Tacubaya', 'Colonia', '1401'),
	(443, '1220', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Zenón Delgado', 'Colonia', '1401'),
	(444, '1619', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Rinconada de Tarango', 'Colonia', '1401'),
	(445, '1620', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Tarango', 'Colonia', '1401'),
	(446, '1630', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Puerta Grande', 'Colonia', '1401'),
	(447, '1630', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Puerta Grande', 'Colonia', '1401'),
	(448, '1630', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Los Juristas', 'Colonia', '1401'),
	(449, '1640', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Herón Proal', 'Colonia', '1401'),
	(450, '1645', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ponciano Arriaga', 'Colonia', '1401'),
	(451, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Milagrosa', 'Colonia', '1401'),
	(452, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Palmas Axotitla', 'Colonia', '1401'),
	(453, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tlacuitlapa', 'Colonia', '1401'),
	(454, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación Tlacuitlapa', 'Colonia', '1401'),
	(455, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '2o Reacomodo Tlacuitlapa', 'Colonia', '1401'),
	(456, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Ruedo', 'Colonia', '1401'),
	(457, '1650', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Santa Lucía Chantepec', 'Colonia', '1401'),
	(458, '1700', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Joyita del Pueblo Tetelpan', 'Colonia', '1001'),
	(459, '1700', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ocotillos del Pueblo Tetelpan', 'Colonia', '1001'),
	(460, '1700', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Agustín del Pueblo Tetelpan', 'Colonia', '1001'),
	(461, '1700', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', '2a Del Moral del Pueblo Tetelpan', 'Colonia', '1001'),
	(462, '1700', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tecalcapa del Pueblo Tetelpan', 'Colonia', '1001'),
	(463, '1700', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tetelpan', 'Pueblo', '1001'),
	(464, '1708', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Encino del Pueblo Tetelpan', 'Colonia', '1001'),
	(465, '1708', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'El Mirador del Pueblo Tetelpan', 'Colonia', '1001'),
	(466, '1710', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Las Águilas', 'Colonia', '1001'),
	(467, '1710', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación Alpes', 'Colonia', '1001'),
	(468, '1720', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de Guadalupe', 'Colonia', '1001'),
	(469, '1729', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Alcantarilla', 'Colonia', '1001'),
	(470, '1730', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de las Águilas', 'Colonia', '1001'),
	(471, '1730', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Puente Colorado', 'Colonia', '1001'),
	(472, '1740', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Peñita del Pueblo Tetelpan', 'Colonia', '1001'),
	(473, '1740', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Clemente Norte', 'Colonia', '1001'),
	(474, '1740', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Clemente Sur', 'Colonia', '1001'),
	(475, '1750', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Las Águilas 1a Sección', 'Colonia', '1001'),
	(476, '1750', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Las Águilas 2o Parque', 'Colonia', '1001'),
	(477, '1750', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Las Águilas 3er Parque', 'Colonia', '1001'),
	(478, '1759', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Ampliación Las Águilas', 'Colonia', '1001'),
	(479, '1760', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Atlamaya', 'Colonia', '1001'),
	(480, '1760', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Flor de María', 'Colonia', '1001'),
	(481, '1760', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Herradura del Pueblo Tetelpan', 'Colonia', '1001'),
	(482, '1770', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'La Angostura', 'Colonia', '1001'),
	(483, '1770', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San José del Olivar', 'Colonia', '1001'),
	(484, '1780', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Olivar de los Padres', 'Colonia', '1001'),
	(485, '1780', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Tizampampano del Pueblo Tetelpan', 'Colonia', '1001'),
	(486, '1789', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Miguel Hidalgo', 'Colonia', '1001'),
	(487, '1790', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de los Ángeles del Pueblo Tetelpan', 'Colonia', '1001'),
	(488, '1790', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'Lomas de San Ángel Inn', 'Colonia', '1001'),
	(489, '1800', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Bartolo Ameyalco', 'Pueblo', '1001'),
	(490, '1800', 'Ciudad de México', 'Álvaro Obregón', 'Ciudad de México', 'San Bartolo Ameyalco', 'Pueblo', '1001');
/*!40000 ALTER TABLE `zip_codes` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
